# Generated by Django 4.1.3 on 2023-04-15 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveSmallIntegerField()),
                ('duration', models.CharField(
                    default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_reference', models.CharField(
                    max_length=100, primary_key=True, serialize=False, unique=True)),
                ('transaction_id', models.CharField(
                    default=None, max_length=100, null=True, unique=True)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('redirect_url', models.TextField(default='')),
                ('payment_options', models.CharField(
                    default='card, mpesa', max_length=100)),
                ('payment_link', models.TextField(default=None, null=True)),
                ('payment_link_status', models.CharField(
                    default=None, max_length=50, null=True)),
                ('payment_link_message', models.CharField(
                    default=None, max_length=50, null=True)),
                ('payment_status', models.CharField(
                    default=None, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expires', models.DateTimeField(default=None, null=True)),
                ('plan', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.paymentplan')),
                ('user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
