# Generated by Django 4.1.3 on 2023-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
