# Generated by Django 4.1.3 on 2023-04-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_active_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created']},
        ),
    ]
