# Generated by Django 4.1.3 on 2023-06-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_options_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sub_active_status',
            field=models.BooleanField(default=False),
        ),
    ]
