# Generated by Django 4.1.3 on 2023-04-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=5000, verbose_name='Content Description')),
                ('image', models.CharField(max_length=500, verbose_name='thumbnail')),
                ('movie', models.CharField(blank=True, max_length=500)),
                ('contentTheme', models.CharField(choices=[('Family', 'FAMILY'), ('Lifestyle', 'LIFESTYLE'), ('Kids', 'KIDS'), ('Animation', 'ANIMATIONS')], default='Family', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('converted_path', models.CharField(max_length=500, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'Movie',
            },
        ),
        migrations.CreateModel(
            name='podcastDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc', models.TextField(max_length=5000, verbose_name='Podcast Description')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='thumbnail')),
                ('contentTheme', models.CharField(choices=[('Family', 'FAMILY'), ('Lifestyle', 'LIFESTYLE'), ('Kids', 'KIDS'), ('Animation', 'ANIMATIONS')], default='Lifestyle', max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'Podcast Detail',
            },
        ),
        migrations.CreateModel(
            name='RSSFeedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('contentTheme', models.CharField(choices=[('Family', 'FAMILY'), ('Lifestyle', 'LIFESTYLE'), ('Kids', 'KIDS'), ('Animation', 'ANIMATIONS')], default='Lifestyle', max_length=50)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='seasonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(help_text='season number')),
                ('desc', models.TextField(blank=True, max_length=5000, verbose_name='Show Description')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='thumbnail')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'Season Detail',
            },
        ),
        migrations.CreateModel(
            name='seasonEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeTitle', models.CharField(blank=True, max_length=50)),
                ('episodeDesc', models.TextField(blank=True, max_length=5000)),
                ('episode', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('converted_path', models.CharField(max_length=500, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('seasonDetail', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='seasonEpisodes', related_query_name='seasonEpisode', to='content.seasondetails')),
            ],
            options={
                'verbose_name': 'Series Episode',
            },
        ),
        migrations.CreateModel(
            name='showDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=5000, verbose_name='show Description')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='thumbnail')),
                ('contentTheme', models.CharField(choices=[('Family', 'FAMILY'), ('Lifestyle', 'LIFESTYLE'), ('Kids', 'KIDS'), ('Animation', 'ANIMATIONS')], default='Family', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'Show Detail',
            },
        ),
        migrations.CreateModel(
            name='showMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(blank=True, max_length=500)),
                ('year', models.IntegerField(blank=True, max_length=500, null=True)),
                ('showDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='show_detail_metadata', to='content.showdetails')),
            ],
        ),
        migrations.CreateModel(
            name='showEpisodesMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('seasonEpisode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_metadata', to='content.seasonepisodes')),
            ],
        ),
        migrations.AddField(
            model_name='seasonepisodes',
            name='showDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.showdetails'),
        ),
        migrations.AddField(
            model_name='seasondetails',
            name='showDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', related_query_name='season', to='content.showdetails'),
        ),
        migrations.CreateModel(
            name='RSSMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=500)),
                ('rssDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rss_detail_metadata', to='content.rssfeeddetails')),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeTitle', models.CharField(max_length=300)),
                ('episodeDesc', models.TextField(max_length=5000)),
                ('episode', models.URLField()),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('rssFeedDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', related_query_name='feed', to='content.rssfeeddetails')),
            ],
        ),
        migrations.CreateModel(
            name='RSSEpisodesMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('rssEpisode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_episode_metadata', to='content.rssfeeditems')),
            ],
        ),
        migrations.CreateModel(
            name='podcastEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeTitle', models.CharField(blank=True, max_length=500)),
                ('episodeDesc', models.TextField(max_length=5000, verbose_name='Episode Description')),
                ('episode', models.CharField(blank=True, max_length=500, verbose_name='Podcast Episode')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('converted_path', models.CharField(max_length=500, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('podcastDetails', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='podcastepisodes', related_query_name='podcastepisode', to='content.podcastdetails')),
            ],
            options={
                'verbose_name': 'Podcast Episodes',
            },
        ),
        migrations.CreateModel(
            name='podcastEpisodeMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('podcastEpisode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_episode_metadata', to='content.podcastepisodes')),
            ],
        ),
        migrations.CreateModel(
            name='podcastDetailMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=500)),
                ('podcastDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_detail_metadata', to='content.podcastdetails')),
            ],
        ),
        migrations.CreateModel(
            name='movieMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=500)),
                ('year', models.IntegerField(blank=True, max_length=500, null=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie_metadata', related_query_name='movie_metadata', to='content.movies')),
            ],
        ),
    ]
