# Generated by Django 4.1.3 on 2023-04-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemetadata',
            old_name='movie',
            new_name='movieDetail',
        ),
        migrations.RenameField(
            model_name='podcastepisodes',
            old_name='podcastDetails',
            new_name='podcastDetail',
        ),
    ]
